### ISSUE TITLE
Does not install dependencies. Is this by design?

### ISSUE THREAD

**Issue by Shkrt** [rdp/specific_install#43]
For example:
```
$ gem specific_install 'rails/rails'
```
or 
```
$ gem specific_install 'https://github.com/rails/rails.git'
```
or
```
$ gem specific_install -l 'https://github.com/rails/rails.git'
```
results in:
```
$ ERROR:  While executing gem ... (Gem::UnsatisfiableDependencyError)
    Unable to resolve dependency: 'rails (= 5.2.0.alpha)' requires 'railties (= 5.2.0.alpha)'
```
and if we start to install dependencies one-by-one, we also got stuck:
```
$ gem specific_install 'https://github.com/rails/rails.git' -d activesupport`  # -Success
$ gem list activesupport 
$ activesupport (5.2.0.alpha, 5.1.4)
$ gem specific_install 'https://github.com/rails/rails.git' -d actionview
$ ERROR:  While executing gem ... (Gem::DependencyError)
    Unresolved dependency found during sorting - activesupport (>= 4.2.0) (requested by rails-dom-testing-2.0.3)
```
The second one, I think, is related to rubygems. But is there a convenient way to install 'rails/rails' using specific_install? In some particular scenarios I am not able to use bundler.

**Comment by rdp** [comment]
Can you think of an easy way to fix this command line wise?

**Comment by Shkrt** [comment]
Will think of solving it, but I've yet to figure out the case with nested prerelease dependencies, because with `Gem::DependencyInstaller.new(prerelease: true).install dep_name` we can install 'rails/rails' repository step-by-step:
```
$ gem specific_install 'https://github.com/rails/rails.git' -d actionview
```
but the following
```
$ gem specific_install 'rails/rails'
```
keeps failing

**Comment by rdp** [comment]
I'm not sure if rubygems has a way to do dependencies while building a
local gem unfortunately...

**Comment by basicfeatures** [comment]
Any news on this?

Trying to `gem specific_install --user-install https://github.com/rails/rails` for version `7.1.0-alpha` but:

```
% gem specific_install --user-install https://github.com/rails/rails.git -d actionpack railties actionview actioncable actionmailbox actionmailer actiontext activejob activemodel activerecord activestorage activesupport
git version 2.37.3
git installing from https://github.com/rails/rails.git
Cloning into '/tmp/d20230204-27124-t48i9k'...
remote: Enumerating objects: 820996, done.
remote: Counting objects: 100% (94/94), done.
remote: Compressing objects: 100% (81/81), done.
remote: Total 820996 (delta 36), reused 22 (delta 10), pack-reused 820902
Receiving objects: 100% (820996/820996), 246.70 MiB | 10.68 MiB/s, done.
Resolving deltas: 100% (611618/611618), done.
Updating files: 100% (4516/4516), done.
Updated 0 paths from the index
fatal: Cannot do hard reset with paths.
ERROR:  While executing gem ... (RuntimeError)
    '$ git reset --hard actionview' exited with an error
    /home/dev/.local/share/gem/ruby/3.1/gems/specific_install-0.3.8/lib/rubygems/commands/specific_install_command.rb:75:in `git'
    /home/dev/.local/share/gem/ruby/3.1/gems/specific_install-0.3.8/lib/rubygems/commands/specific_install_command.rb:249:in `reset_to_commit'
    /home/dev/.local/share/gem/ruby/3.1/gems/specific_install-0.3.8/lib/rubygems/commands/specific_install_command.rb:157:in `block in install_from_git'
    /home/dev/.local/share/gem/ruby/3.1/gems/specific_install-0.3.8/lib/rubygems/commands/specific_install_command.rb:155:in `chdir'
    /home/dev/.local/share/gem/ruby/3.1/gems/specific_install-0.3.8/lib/rubygems/commands/specific_install_command.rb:155:in `install_from_git'
    /home/dev/.local/share/gem/ruby/3.1/gems/specific_install-0.3.8/lib/rubygems/commands/specific_install_command.rb:135:in `install_git'
    /home/dev/.local/share/gem/ruby/3.1/gems/specific_install-0.3.8/lib/rubygems/commands/specific_install_command.rb:90:in `determine_source_and_install'
    /home/dev/.local/share/gem/ruby/3.1/gems/specific_install-0.3.8/lib/rubygems/commands/specific_install_command.rb:67:in `block in execute'
    /usr/local/lib/ruby/3.1/tmpdir.rb:96:in `mktmpdir'
    /home/dev/.local/share/gem/ruby/3.1/gems/specific_install-0.3.8/lib/rubygems/commands/specific_install_command.rb:59:in `execute'
    /usr/local/lib/ruby/3.1/rubygems/command.rb:323:in `invoke_with_build_args'
    /usr/local/lib/ruby/3.1/rubygems/command_manager.rb:185:in `process_args'
    /usr/local/lib/ruby/3.1/rubygems/command_manager.rb:149:in `run'
    /usr/local/lib/ruby/3.1/rubygems/gem_runner.rb:51:in `run'
    /usr/local/bin/gem:21:in `<main>'
```

**Comment by rdp** [comment]
OK attempted to merge it, give it a try sometime :)
